import { useTranslations } from 'next-intl';

type Values = {
  value: string;
  label: string;
};

export function getRoles(): Array<Values> {
  const t = useTranslations('VerificationPage');

  const roles = [
    { value: 'Agent', label: t('roleAgent') },
    { value: 'Agency', label: t('roleAgency') },
  ];

  return roles;
}

export function getGenders(): Array<Values> {
  const t = useTranslations('VerificationPage');

  const genders = [
    { value: 'Male', label: t('genderMale') },
    { value: 'Female', label: t('genderFemale') },
    { value: 'Other', label: t('genderOther') },
  ];

  return genders;
}

export function getIdentities(): Array<Values> {
  const t = useTranslations('VerificationPage');

  const identities = [
    { value: 'Passport', label: t('proofPassport') },
    { value: 'ID', label: t('proofId') },
    { value: 'Driving licence', label: t('proofDL') },
  ];

  return identities;
}

export function getStatuses(): Array<Values> {
  const t = useTranslations('VerificationPage');

  const statuses = [
    { value: 'Resident Individual', label: t('statusResident') },
    { value: 'Non Resident', label: t('statusNonResident') },
    { value: 'Foreign National', label: t('statusForeign') },
  ];

  return statuses;
}

export function getCountries(): Array<Values> {
  const countries = [
    { value: 'AD', label: 'Andorra' },
    { value: 'AE', label: 'United Arab Emirates' },
    { value: 'AF', label: 'Afghanistan' },
    { value: 'AG', label: 'Antigua and Barbuda' },
    { value: 'AI', label: 'Anguilla' },
    { value: 'AL', label: 'Albania' },
    { value: 'AM', label: 'Armenia' },
    { value: 'AO', label: 'Angola' },
    { value: 'AQ', label: 'Antarctica' },
    { value: 'AR', label: 'Argentina' },
    { value: 'AS', label: 'American Samoa' },
    { value: 'AT', label: 'Austria' },
    { value: 'AU', label: 'Australia' },
    { value: 'AW', label: 'Aruba' },
    { value: 'AX', label: 'Alland Islands' },
    { value: 'AZ', label: 'Azerbaijan' },
    { value: 'BA', label: 'Bosnia and Herzegovina' },
    { value: 'BB', label: 'Barbados' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BE', label: 'Belgium' },
    { value: 'BF', label: 'Burkina Faso' },
    { value: 'BG', label: 'Bulgaria' },
    { value: 'BH', label: 'Bahrain' },
    { value: 'BI', label: 'Burundi' },
    { value: 'BJ', label: 'Benin' },
    { value: 'BL', label: 'Saint Barthelemy' },
    { value: 'BM', label: 'Bermuda' },
    { value: 'BN', label: 'Brunei Darussalam' },
    { value: 'BO', label: 'Bolivia' },
    { value: 'BR', label: 'Brazil' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BT', label: 'Bhutan' },
    { value: 'BV', label: 'Bouvet Island' },
    { value: 'BW', label: 'Botswana' },
    { value: 'BY', label: 'Belarus' },
    { value: 'BZ', label: 'Belize' },
    { value: 'CA', label: 'Canada' },
    { value: 'CC', label: 'Cocos (Keeling) Islands' },
    { value: 'CD', label: 'Congo, Democratic Republic of the' },
    { value: 'CF', label: 'Central African Republic' },
    { value: 'CG', label: 'Congo, Republic of the' },
    { value: 'CH', label: 'Switzerland' },
    { value: 'CI', label: "Cote d'Ivoire" },
    { value: 'CK', label: 'Cook Islands' },
    { value: 'CL', label: 'Chile' },
    { value: 'CM', label: 'Cameroon' },
    { value: 'CN', label: 'China' },
    { value: 'CO', label: 'Colombia' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'CU', label: 'Cuba' },
    { value: 'CV', label: 'Cape Verde' },
    { value: 'CW', label: 'Curacao' },
    { value: 'CX', label: 'Christmas Island' },
    { value: 'CY', label: 'Cyprus' },
    { value: 'CZ', label: 'Czech Republic' },
    { value: 'DE', label: 'Germany' },
    { value: 'DJ', label: 'Djibouti' },
    { value: 'DK', label: 'Denmark' },
    { value: 'DM', label: 'Dominica' },
    { value: 'DO', label: 'Dominican Republic' },
    { value: 'DZ', label: 'Algeria' },
    { value: 'EC', label: 'Ecuador' },
    { value: 'EE', label: 'Estonia' },
    { value: 'EG', label: 'Egypt' },
    { value: 'EH', label: 'Western Sahara' },
    { value: 'ER', label: 'Eritrea' },
    { value: 'ES', label: 'Spain' },
    { value: 'ET', label: 'Ethiopia' },
    { value: 'FI', label: 'Finland' },
    { value: 'FJ', label: 'Fiji' },
    { value: 'FK', label: 'Falkland Islands (Malvinas)' },
    { value: 'FM', label: 'Micronesia, Federated States of' },
    { value: 'FO', label: 'Faroe Islands' },
    { value: 'FR', label: 'France' },
    { value: 'GA', label: 'Gabon' },
    { value: 'GB', label: 'United Kingdom' },
    { value: 'GD', label: 'Grenada' },
    { value: 'GE', label: 'Georgia' },
    { value: 'GF', label: 'French Guiana' },
    { value: 'GG', label: 'Guernsey' },
    { value: 'GH', label: 'Ghana' },
    { value: 'GI', label: 'Gibraltar' },
    { value: 'GL', label: 'Greenland' },
    { value: 'GM', label: 'Gambia' },
    { value: 'GN', label: 'Guinea' },
    { value: 'GP', label: 'Guadeloupe' },
    { value: 'GQ', label: 'Equatorial Guinea' },
    { value: 'GR', label: 'Greece' },
    { value: 'GS', label: 'South Georgia and the South Sandwich Islands' },
    { value: 'GT', label: 'Guatemala' },
    { value: 'GU', label: 'Guam' },
    { value: 'GW', label: 'Guinea-Bissau' },
    { value: 'GY', label: 'Guyana' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'HM', label: 'Heard Island and McDonald Islands' },
    { value: 'HN', label: 'Honduras' },
    { value: 'HR', label: 'Croatia' },
    { value: 'HT', label: 'Haiti' },
    { value: 'HU', label: 'Hungary' },
    { value: 'ID', label: 'Indonesia' },
    { value: 'IE', label: 'Ireland' },
    { value: 'IL', label: 'Israel' },
    { value: 'IM', label: 'Isle of Man' },
    { value: 'IN', label: 'India' },
    { value: 'IO', label: 'British Indian Ocean Territory' },
    { value: 'IQ', label: 'Iraq' },
    { value: 'IR', label: 'Iran, Islamic Republic of' },
    { value: 'IS', label: 'Iceland' },
    { value: 'IT', label: 'Italy' },
    { value: 'JE', label: 'Jersey' },
    { value: 'JM', label: 'Jamaica' },
    { value: 'JO', label: 'Jordan' },
    { value: 'JP', label: 'Japan' },
    { value: 'KE', label: 'Kenya' },
    { value: 'KG', label: 'Kyrgyzstan' },
    { value: 'KH', label: 'Cambodia' },
    { value: 'KI', label: 'Kiribati' },
    { value: 'KM', label: 'Comoros' },
    { value: 'KN', label: 'Saint Kitts and Nevis' },
    { value: 'KP', label: "Korea, Democratic People's Republic of" },
    { value: 'KR', label: 'Korea, Republic of' },
    { value: 'KW', label: 'Kuwait' },
    { value: 'KY', label: 'Cayman Islands' },
    { value: 'KZ', label: 'Kazakhstan' },
    { value: 'LA', label: "Lao People's Democratic Republic" },
    { value: 'LB', label: 'Lebanon' },
    { value: 'LC', label: 'Saint Lucia' },
    { value: 'LI', label: 'Liechtenstein' },
    { value: 'LK', label: 'Sri Lanka' },
    { value: 'LR', label: 'Liberia' },
    { value: 'LS', label: 'Lesotho' },
    { value: 'LT', label: 'Lithuania' },
    { value: 'LU', label: 'Luxembourg' },
    { value: 'LV', label: 'Latvia' },
    { value: 'LY', label: 'Libya' },
    { value: 'MA', label: 'Morocco' },
    { value: 'MC', label: 'Monaco' },
    { value: 'MD', label: 'Moldova, Republic of' },
    { value: 'ME', label: 'Montenegro' },
    { value: 'MF', label: 'Saint Martin (French part)' },
    { value: 'MG', label: 'Madagascar' },
    { value: 'MH', label: 'Marshall Islands' },
    { value: 'MK', label: 'Macedonia, the Former Yugoslav Republic of' },
    { value: 'ML', label: 'Mali' },
    { value: 'MM', label: 'Myanmar' },
    { value: 'MN', label: 'Mongolia' },
    { value: 'MO', label: 'Macao' },
    { value: 'MP', label: 'Northern Mariana Islands' },
    { value: 'MQ', label: 'Martinique' },
    { value: 'MR', label: 'Mauritania' },
    { value: 'MS', label: 'Montserrat' },
    { value: 'MT', label: 'Malta' },
    { value: 'MU', label: 'Mauritius' },
    { value: 'MV', label: 'Maldives' },
    { value: 'MW', label: 'Malawi' },
    { value: 'MX', label: 'Mexico' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'MZ', label: 'Mozambique' },
    { value: 'NA', label: 'Namibia' },
    { value: 'NC', label: 'New Caledonia' },
    { value: 'NE', label: 'Niger' },
    { value: 'NF', label: 'Norfolk Island' },
    { value: 'NG', label: 'Nigeria' },
    { value: 'NI', label: 'Nicaragua' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'NO', label: 'Norway' },
    { value: 'NP', label: 'Nepal' },
    { value: 'NR', label: 'Nauru' },
    { value: 'NU', label: 'Niue' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'OM', label: 'Oman' },
    { value: 'PA', label: 'Panama' },
    { value: 'PE', label: 'Peru' },
    { value: 'PF', label: 'French Polynesia' },
    { value: 'PG', label: 'Papua New Guinea' },
    { value: 'PH', label: 'Philippines' },
    { value: 'PK', label: 'Pakistan' },
    { value: 'PL', label: 'Poland' },
    { value: 'PM', label: 'Saint Pierre and Miquelon' },
    { value: 'PN', label: 'Pitcairn' },
    { value: 'PR', label: 'Puerto Rico' },
    { value: 'PS', label: 'Palestine, State of' },
    { value: 'PT', label: 'Portugal' },
    { value: 'PW', label: 'Palau' },
    { value: 'PY', label: 'Paraguay' },
    { value: 'QA', label: 'Qatar' },
    { value: 'RE', label: 'Reunion' },
    { value: 'RO', label: 'Romania' },
    { value: 'RS', label: 'Serbia' },
    { value: 'RU', label: 'Russian Federation' },
    { value: 'RW', label: 'Rwanda' },
    { value: 'SA', label: 'Saudi Arabia' },
    { value: 'SB', label: 'Solomon Islands' },
    { value: 'SC', label: 'Seychelles' },
    { value: 'SD', label: 'Sudan' },
    { value: 'SE', label: 'Sweden' },
    { value: 'SG', label: 'Singapore' },
    { value: 'SH', label: 'Saint Helena' },
    { value: 'SI', label: 'Slovenia' },
    { value: 'SJ', label: 'Svalbard and Jan Mayen' },
    { value: 'SK', label: 'Slovakia' },
    { value: 'SL', label: 'Sierra Leone' },
    { value: 'SM', label: 'San Marino' },
    { value: 'SN', label: 'Senegal' },
    { value: 'SO', label: 'Somalia' },
    { value: 'SR', label: 'Suriname' },
    { value: 'SS', label: 'South Sudan' },
    { value: 'ST', label: 'Sao Tome and Principe' },
    { value: 'SV', label: 'El Salvador' },
    { value: 'SX', label: 'Sint Maarten (Dutch part)' },
    { value: 'SY', label: 'Syrian Arab Republic' },
    { value: 'SZ', label: 'Swaziland' },
    { value: 'TC', label: 'Turks and Caicos Islands' },
    { value: 'TD', label: 'Chad' },
    { value: 'TF', label: 'French Southern Territories' },
    { value: 'TG', label: 'Togo' },
    { value: 'TH', label: 'Thailand' },
    { value: 'TJ', label: 'Tajikistan' },
    { value: 'TK', label: 'Tokelau' },
    { value: 'TL', label: 'Timor-Leste' },
    { value: 'TM', label: 'Turkmenistan' },
    { value: 'TN', label: 'Tunisia' },
    { value: 'TO', label: 'Tonga' },
    { value: 'TR', label: 'Turkey' },
    { value: 'TT', label: 'Trinidad and Tobago' },
    { value: 'TV', label: 'Tuvalu' },
    { value: 'TW', label: 'Taiwan' },
    { value: 'TZ', label: 'United Republic of Tanzania' },
    { value: 'UA', label: 'Ukraine' },
    { value: 'UG', label: 'Uganda' },
    { value: 'US', label: 'United States' },
    { value: 'UY', label: 'Uruguay' },
    { value: 'UZ', label: 'Uzbekistan' },
    { value: 'VA', label: 'Holy See (Vatican City State)' },
    { value: 'VC', label: 'Saint Vincent and the Grenadines' },
    { value: 'VE', label: 'Venezuela' },
    { value: 'VG', label: 'British Virgin Islands' },
    { value: 'VI', label: 'US Virgin Islands' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'VU', label: 'Vanuatu' },
    { value: 'WF', label: 'Wallis and Futuna' },
    { value: 'WS', label: 'Samoa' },
    { value: 'XK', label: 'Kosovo' },
    { value: 'YE', label: 'Yemen' },
    { value: 'YT', label: 'Mayotte' },
    { value: 'ZA', label: 'South Africa' },
    { value: 'ZM', label: 'Zambia' },
    { value: 'ZW', label: 'Zimbabwe' },
  ];

  return countries;
}

export function getNationalities(): Array<Values> {
  const nationalities = [
    { value: '1', label: 'Afghan' },
    { value: '2', label: 'Albanian' },
    { value: '3', label: 'Algerian' },
    { value: '4', label: 'American' },
    { value: '5', label: 'Andorran' },
    { value: '6', label: 'Angolan' },
    { value: '7', label: 'Antiguans' },
    { value: '8', label: 'Argentinean' },
    { value: '9', label: 'Armenian' },
    { value: '10', label: 'Australian' },
    { value: '11', label: 'Austrian' },
    { value: '12', label: 'Azerbaijani' },
    { value: '13', label: 'Bahamian' },
    { value: '14', label: 'Bahraini' },
    { value: '15', label: 'Bangladeshi' },
    { value: '16', label: 'Barbadian' },
    { value: '17', label: 'Barbudans' },
    { value: '18', label: 'Batswana' },
    { value: '19', label: 'Belarusian' },
    { value: '20', label: 'Belgian' },
    { value: '21', label: 'Belizean' },
    { value: '22', label: 'Beninese' },
    { value: '23', label: 'Bhutanese' },
    { value: '24', label: 'Bolivian' },
    { value: '25', label: 'Bosnian' },
    { value: '26', label: 'Brazilian' },
    { value: '27', label: 'British' },
    { value: '28', label: 'Bruneian' },
    { value: '29', label: 'Bulgarian' },
    { value: '30', label: 'Burkinabe' },
    { value: '31', label: 'Burmese' },
    { value: '32', label: 'Burundian' },
    { value: '33', label: 'Cambodian' },
    { value: '34', label: 'Cameroonian' },
    { value: '35', label: 'Canadian' },
    { value: '36', label: 'Cape Verdean' },
    { value: '37', label: 'Central African' },
    { value: '38', label: 'Chadian' },
    { value: '39', label: 'Chilean' },
    { value: '40', label: 'Chinese' },
    { value: '41', label: 'Colombian' },
    { value: '42', label: 'Comoran' },
    { value: '43', label: 'Congolese' },
    { value: '44', label: 'Costa Rican' },
    { value: '45', label: 'Croatian' },
    { value: '46', label: 'Cuban' },
    { value: '47', label: 'Cypriot' },
    { value: '48', label: 'Czech' },
    { value: '49', label: 'Danish' },
    { value: '50', label: 'Djibouti' },
    { value: '51', label: 'Dominican' },
    { value: '52', label: 'Dutch' },
    { value: '53', label: 'East Timorese' },
    { value: '54', label: 'Ecuadorean' },
    { value: '55', label: 'Egyptian' },
    { value: '56', label: 'Emirian' },
    { value: '57', label: 'Equatorial Guinean' },
    { value: '58', label: 'Eritrean' },
    { value: '59', label: 'Estonian' },
    { value: '60', label: 'Ethiopian' },
    { value: '61', label: 'Fijian' },
    { value: '62', label: 'Filipino' },
    { value: '63', label: 'Finnish' },
    { value: '64', label: 'French' },
    { value: '65', label: 'Gabonese' },
    { value: '66', label: 'Gambian' },
    { value: '67', label: 'Georgian' },
    { value: '68', label: 'German' },
    { value: '69', label: 'Ghanaian' },
    { value: '70', label: 'Greek' },
    { value: '71', label: 'Grenadian' },
    { value: '72', label: 'Guatemalan' },
    { value: '73', label: 'Guinea-Bissauan' },
    { value: '74', label: 'Guinean' },
    { value: '75', label: 'Guyanese' },
    { value: '76', label: 'Haitian' },
    { value: '77', label: 'Herzegovinian' },
    { value: '78', label: 'Honduran' },
    { value: '79', label: 'Hungarian' },
    { value: '80', label: 'I-Kiribati' },
    { value: '81', label: 'Icelander' },
    { value: '82', label: 'Indian' },
    { value: '83', label: 'Indonesian' },
    { value: '84', label: 'Iranian' },
    { value: '85', label: 'Iraqi' },
    { value: '86', label: 'Irish' },
    { value: '87', label: 'Israeli' },
    { value: '88', label: 'Italian' },
    { value: '89', label: 'Ivorian' },
    { value: '90', label: 'Jamaican' },
    { value: '91', label: 'Japanese' },
    { value: '92', label: 'Jordanian' },
    { value: '93', label: 'Kazakhstani' },
    { value: '94', label: 'Kenyan' },
    { value: '95', label: 'Kittian and Nevisian' },
    { value: '96', label: 'Kuwaiti' },
    { value: '97', label: 'Kyrgyz' },
    { value: '98', label: 'Laotian' },
    { value: '99', label: 'Latvian' },
    { value: '100', label: 'Lebanese' },
    { value: '101', label: 'Liberian' },
    { value: '102', label: 'Libyan' },
    { value: '103', label: 'Liechtensteiner' },
    { value: '104', label: 'Lithuanian' },
    { value: '105', label: 'Luxembourger' },
    { value: '106', label: 'Macedonian' },
    { value: '107', label: 'Malagasy' },
    { value: '108', label: 'Malawian' },
    { value: '109', label: 'Malaysian' },
    { value: '110', label: 'Maldivan' },
    { value: '111', label: 'Malian' },
    { value: '112', label: 'Maltese' },
    { value: '113', label: 'Marshallese' },
    { value: '114', label: 'Mauritanian' },
    { value: '115', label: 'Mauritian' },
    { value: '116', label: 'Mexican' },
    { value: '117', label: 'Micronesian' },
    { value: '118', label: 'Moldovan' },
    { value: '119', label: 'Monacan' },
    { value: '120', label: 'Mongolian' },
    { value: '121', label: 'Moroccan' },
    { value: '122', label: 'Mosotho' },
    { value: '123', label: 'Motswana' },
    { value: '124', label: 'Mozambican' },
    { value: '125', label: 'Namibian' },
    { value: '126', label: 'Nauruan' },
    { value: '127', label: 'Nepali' },
    { value: '128', label: 'New Zealander' },
    { value: '129', label: 'Nicaraguan' },
    { value: '130', label: 'Nigerian' },
    { value: '131', label: 'Nigerien' },
    { value: '132', label: 'North Korean' },
    { value: '133', label: 'Northern Irish' },
    { value: '134', label: 'Norwegian' },
    { value: '135', label: 'Omani' },
    { value: '136', label: 'Pakistani' },
    { value: '137', label: 'Palauan' },
    { value: '138', label: 'Panamanian' },
    { value: '139', label: 'Papua New Guinean' },
    { value: '140', label: 'Paraguayan' },
    { value: '141', label: 'Peruvian' },
    { value: '142', label: 'Polish' },
    { value: '143', label: 'Portuguese' },
    { value: '144', label: 'Qatari' },
    { value: '145', label: 'Romanian' },
    { value: '146', label: 'Russian' },
    { value: '147', label: 'Rwandan' },
    { value: '148', label: 'Saint Lucian' },
    { value: '149', label: 'Salvadoran' },
    { value: '150', label: 'Samoan' },
    { value: '151', label: 'San Marinese' },
    { value: '152', label: 'Sao Tomean' },
    { value: '153', label: 'Saudi' },
    { value: '154', label: 'Scottish' },
    { value: '155', label: 'Senegalese' },
    { value: '156', label: 'Serbian' },
    { value: '157', label: 'Seychellois' },
    { value: '158', label: 'Sierra Leonean' },
    { value: '159', label: 'Singaporean' },
    { value: '160', label: 'Slovakian' },
    { value: '161', label: 'Slovenian' },
    { value: '162', label: 'Solomon Islander' },
    { value: '163', label: 'Somali' },
    { value: '164', label: 'South African' },
    { value: '165', label: 'South Korean' },
    { value: '166', label: 'Spanish' },
    { value: '167', label: 'Sri Lankan' },
    { value: '168', label: 'Sudanese' },
    { value: '169', label: 'Surinamer' },
    { value: '170', label: 'Swazi' },
    { value: '171', label: 'Swedish' },
    { value: '172', label: 'Swiss' },
    { value: '173', label: 'Syrian' },
    { value: '174', label: 'Taiwanese' },
    { value: '175', label: 'Tajik' },
    { value: '176', label: 'Tanzanian' },
    { value: '177', label: 'Thai' },
    { value: '178', label: 'Togolese' },
    { value: '179', label: 'Tongan' },
    { value: '180', label: 'Trinidadian/Tobagonian' },
    { value: '181', label: 'Tunisian' },
    { value: '182', label: 'Turkish' },
    { value: '183', label: 'Tuvaluan' },
    { value: '184', label: 'Ugandan' },
    { value: '185', label: 'Ukrainian' },
    { value: '186', label: 'Uruguayan' },
    { value: '187', label: 'Uzbekistani' },
    { value: '188', label: 'Venezuelan' },
    { value: '189', label: 'Vietnamese' },
    { value: '190', label: 'Welsh' },
    { value: '191', label: 'Yemenite' },
    { value: '192', label: 'Zambian' },
    { value: '193', label: 'Zimbabwean' },
  ];

  return nationalities;
}
