const ApiRoute = {
  SEND_CODE_FOR_RESTORE_PASSWORD: '/email/forgot-password',
  CONFIRM_CODE_FOR_RESTORE_PASSWORD: '/auth/confirm-email',
  CONFIRM_RESTORE_PASSWORD: '/auth/restore-password',
  ADD_VERIFICATION_DATA: '/verification/update',
  UPDATE_PROFILE_DATA: '/user/update',
  SET_AVATAR: '/user/set-avatar',
  DELETE_AVATAR: '/user/delete-avatar',
  GET_USER_BY_ID: '/user/id',
  VERIFY_OLD_PASSWORD: '/auth/verify-password',
  CHANGE_PASSWORD: '/auth/change-password',
  UPDATE_USER: '/user/id',
  DELETE_USER: '/user',
  QOBRIX_CREATE_CONTACT: '/contacts',
  QOBRIX_CREATE_AGENT: '/agents',
  QOBRIX_PROPERY_TYPES: '/property-types',
  QOBRIX_GET_PROPERTIES: '/properties',
  QOBRIX_GET_PROPERTY: '/properties/id',
  GET_LEAD_DETAILS: '/lead/details/id',
  GET_MATCHING_PROPERTIES: 'lead/properties',
  QOBRIX_GET_LEADS: '/opportunities',
  QOBRIX_GET_PROPERTY_LEADS: '/opportunities/by-property/id',
  QOBRIX_GET_LEADS_SMSES: '/sms-messages/related-with/RelatedOpportunityOpportunities/id',
  QOBRIX_GET_LEADS_EMAILS: '/email-messages/related-with/RelatedOpportunityOpportunities/id',
  QOBRIX_GET_LEADS_TASKS: '/tasks/related-with/RelatedOpportunityOpportunities/id',
  QOBRIX_GET_LEADS_MEETINGS: '/meetings/related-with/RelatedOpportunityOpportunities/id',
  QOBRIX_GET_LEADS_CALLS: '/calls/related-with/RelatedOpportunityOpportunities/id',
  QOBRIX_GET_LEADS_TASKS_WORKFLOW: '/workflows/id/stages',
  QOBRIX_GET_LEADS_CHANGELOG: '/opportunities/id/changes',
} as const;

export { ApiRoute };
