export const colors = {
  TEST_BACKGROUND_COLOR: '#172234',
  TEST_MAIN_COLOR: '#808080',
  SIGN_IN_LINKS_COLOR: '#7a4100',
  TEST_SECOND_COLOR: '#FFFDDD',
  PRIMARY_LIGHT_COLOR: '#FFFFFF',
  BUTTON_PRIMARY_COLOR: '#00A76F',
  BUTTON_SECOND_COLOR: '#007867',
  PRIMARY_DARK_COLOR: '#OOOOOO',
};
