export const randomValues = {
  MESSAGES_PAGE: 'Messages Page',
  CHAT_PAGE: 'Chat page',
  BADGE_TEMP_VALUE: 5,
  MSG: 'Message',
  USER: 'User',
  ALL: 'all',
  INFORMATIVE: 'informative',
  PARKING_LOT: 'parking_lot',
  PRICE_FROM: 'price from',
  PRICE_TO: 'price to',
  TYPE: 'type',
  STATUS: 'status',
  BEDROOMS: 'bedrooms',
};
