import { useMemo } from 'react';
import useSWR from 'swr';
// utils
import { endpoints, fetcherQobrix } from 'utils/axios';
// types
import { IPropertyItem, IProperties, IPropertyParams, IPropertyDetailed } from 'types/properties';
import { QOBRIX_KEYS } from 'config-global';

// ----------------------------------------------------------------------

const options = {
  headers: {
    'X-Api-User': QOBRIX_KEYS.apiUser,
    'X-Api-Key': QOBRIX_KEYS.apiKey,
  },
};

const URL = endpoints.property;

// ----------------------------------------------------------------------

export function useGetProperties(params: IPropertyParams) {
  const { data, error } = useSWR([URL.list, { ...options, ...params }], fetcherQobrix);

  if (error) {
    console.error('Error fetching properties:', error);
  }

  const memoizedValue = useMemo(() => {
    const properties = {
      data: data?.data.map((property: IPropertyItem) => ({
        ...property,
        id: property.id,
        saleRent: property.sale_rent,
        status: property.status,
        country: property.country,
        city: property.city,
        price: property.list_selling_price_amount,
        photo: property.media[0].file.thumbnails.medium,
      })),
      pagination: { hasNextPage: data?.pagination.has_next_page },
    };

    return {
      properties: properties as IProperties,
      propertiesError: error,
    };
  }, [data, error]);

  return memoizedValue;
}

// ----------------------------------------------------------------------

export function useGetProperty(id: string) {
  const { error, isLoading } = useSWR([`${URL.list}/${id}`, { ...options }], fetcherQobrix);
  console.log(id);
  if (error) {
    console.error('Error fetching properties:', error);
  }

  const data = mock;
  const memoizedValue = useMemo(() => {
    const property: IPropertyDetailed = {
      saleRent: data?.data.sale_rent,
      status: data?.data.status,
      country: data?.data.country,
      city: data?.data.city,
      price: data?.data.list_selling_price_amount,
      media: data?.data.media,
      description: data?.data.description,
      name: data?.data.name,
      propertyType: data?.data.property_type,
      bedrooms: data?.data.bedrooms,
      bathrooms: data?.data.bathrooms,
      livingrooms: data?.data.living_rooms,
      kitchenType: data?.data.kitchen_type,
      verandas: data?.data.verandas,
      parking: data?.data.parking,
      coordinates: data?.data.coordinates,
      municipality: data?.data.municipality,
      state: data?.data.state,
      postCode: data?.data.post_code,
      street: data?.data.street,
      floorNumber: data?.data.floor_number,
      seaView: data?.data.sea_view,
      mountainView: data?.data.mountain_view,
      privateSwimmingPool: data?.data.private_swimming_pool,
      commonSwimmingPool: data?.data.common_swimming_pool,
      petsAllowed: data?.data.pets_allowed,
      elevator: data?.data.elevator,
      listingDate: data?.data.listing_date,
      internalAreaAmount: data?.data.internal_area_amount,
      coveredVerandasAmount: data?.data.covered_verandas_amount,
      tenancyType: data?.data.tenancy_type,
      communityFeatures: data?.data.community_features,
      sellerName: data?.data.seller_contact.name,
      sellerEmail: data?.data.seller_contact.email,
      sellerPhone: data?.data.seller_contact.phone,
      salespersonUserName: data?.data.salesperson_user.name,
      salespersonUserEmail: data?.data.salesperson_user.username,
    };

    return {
      property: property as IPropertyDetailed,
      propertyLoading: isLoading,
      propertyError: error,
    };
  }, [data, error, isLoading]);

  return memoizedValue;
}

const mock = {
  data: {
    id: '006251f6-39d4-4944-bb2f-c411e0b8d98b',
    ref: 1028,
    description:
      'Renovated Lux Apartment 1 is renovated classical building turned into luxury apartment, Peacefully located in a relaxing neighborhood crossed by the river Tiber in Rome.The property includes two bedrooms and two bathrooms, a terrace, extensive storage space and high tech alarm systems for extra safety. All internal areas are air conditioned and the consumption of electricity is an afterthought with the excellent energy efficiency levels. The whole building is accessible via modern elevator that checks all safety prerequisites.',
    name: 'Renovated Lux Apartment 4',
    unit_number: '',
    property_type: 'apartment',
    status: 'available',
    sale_rent: 'for_sale',
    construction_stage: 'completed',
    bedrooms: 2,
    bathrooms: 2,
    kitchen_type: 'open_plan',
    verandas: null,
    parking: null,
    featured: false,
    featured_priority: null,
    furnished: null,
    created: '2021-05-18T08:23:23+00:00',
    modified: '2021-05-24T07:47:43+00:00',
    created_by: 'ed48f01f-05c3-4c95-9239-c74e1defe96a',
    modified_by: 'ed48f01f-05c3-4c95-9239-c74e1defe96a',
    property_of_the_month: false,
    coordinates: '41.89039417061612,12.480103856381602',
    country: 'IT',
    city: 'Rome',
    municipality: 'Municipio Roma I',
    state: 'Roma Capitale',
    post_code: '',
    street: '',
    uncovered_parking: null,
    covered_parking: null,
    customer_parking: null,
    floor_number: 1,
    office_layout: null,
    wc_bathrooms: null,
    reception: null,
    conference: null,
    server_room: null,
    electricity: null,
    right_of_way: null,
    registered_road: null,
    water: null,
    corner_plot: null,
    land_locked: null,
    elevated_area: null,
    sea_view: null,
    mountain_view: null,
    abuts_green_area: null,
    beach_front: null,
    floors_building: null,
    office_spaces: null,
    store_room: null,
    town_planning_zone: null,
    private_swimming_pool: false,
    common_swimming_pool: false,
    key_holder_details: '',
    kitchenette: null,
    video_link: null,
    virtual_tour_link: null,
    location: '20f1727c-ff8f-4594-8cd6-976c3e6b3d33',
    legacy_id: null,
    agent: null,
    salesperson: 'ed48f01f-05c3-4c95-9239-c74e1defe96a',
    website_status: 'unpublished',
    short_description: '',
    home_office: false,
    separate_laundry_room: false,
    maids_room: false,
    alarm: false,
    air_condition: null,
    elevator: true,
    fireplace: true,
    pets_allowed: true,
    smart_home: false,
    storage_space: false,
    secure_door: null,
    concierge_reception: null,
    seller: '728c634d-62ae-4ed0-a47d-4c043c0c8c33',
    source: 'direct',
    direct_sources: 'walk_in',
    source_description: '',
    listing_date: '2021-05-18',
    engagement_letter_date: null,
    inspection_date: null,
    campaign_id: null,
    heating_type: null,
    heating_medium: null,
    coverage: null,
    building_density: null,
    height: null,
    storeys_max_floor: null,
    ideal_for: null,
    licensed_for: null,
    energy_efficiency_grade: 'a',
    enclosed_office_room: null,
    cooling_type: null,
    internal_area_amount: '80.00',
    covered_verandas_amount: '20.00',
    garden_area_amount: null,
    plot_area_amount: null,
    list_selling_price_amount: '601000.00',
    list_rental_price_amount: null,
    uncovered_area_amount: null,
    covered_area_amount: null,
    uncovered_verandas_amount: null,
    roof_garden_area_amount: null,
    storage_amount: null,
    frontage_amount: null,
    mezzanine_amount: null,
    total_area_amount: null,
    project: '1674024b-3e48-4523-af3a-d29b2901456f',
    construction_type: null,
    electricity_type: null,
    construction_year: null,
    renovation_year: null,
    floor_type: null,
    price_per_square: '7512.50',
    cover_factor: null,
    website_listing_date: null,
    trashed: null,
    inherit_project_media: false,
    price_qualifier: null,
    solar_water_heater: null,
    geocode_type: null,
    group_id: null,
    plus_vat: false,
    auction_start_date: null,
    auction_end_date: null,
    reserve_price_amount: null,
    starting_bidding_amount: null,
    occupancy: null,
    kitchens: null,
    living_rooms: null,
    additional_features: [],
    website_url: null,
    appliances: [],
    association_amenities: [],
    cooling: [],
    community_features: [],
    exterior_features: [],
    heating: [],
    flooring: [],
    interior_features: [],
    lot_features: [],
    other_structures: [],
    patio_porch: [],
    pool_features: [],
    security_features: [],
    view: [],
    waterfront_features: [],
    cloned_from: null,
    property_subtype: 'standard_apartment',
    developer_id: null,
    fencing: [],
    tenancy_type: null,
    rent_frequency: null,
    minimum_tenancy: null,
    fireplace_features: [],
    developer: null,
    group: null,
    PropertyPropertyType: {
      id: 'bff59c2c-b14c-4e50-8a51-32d4e2fe19bd',
      name: 'Apartment',
      code: 'apartment',
      display_order: 2,
      config: null,
      created: '2021-04-07T13:05:01+00:00',
      created_by: null,
      modified_by: null,
      trashed: null,
      modified: '2021-04-07T13:05:01+00:00',
      base_type: 'residential',
    },
    project_project: {
      id: '1674024b-3e48-4523-af3a-d29b2901456f',
      name: 'Ceasar Apartment Complex - Rome',
      reference_code: '',
      housing_type: null,
      project_listing_priority: null,
      short_description: '',
      description:
        'The Caesar Apartment Complex Project was completed in 2019, it undertook the renovation of a total of 25 apartments from classical buildings into modern luxury residences. Five of which remain unsold and are available. Peacefully located in a relaxing neighborhood crossed by the river Tiber.',
      construction_stage: 'completed',
      coordinates: null,
      country: 'IT',
      city: 'Center',
      municipality: '',
      state: 'Rome',
      post_code: '',
      street: '',
      street_2: null,
      featured: false,
      featured_priority: null,
      video_links: null,
      location: 'da49be76-5782-479b-a341-6386832fabb7',
      completion_date: null,
      modified: '2021-05-24T08:18:13+00:00',
      abbreviation: null,
      created: '2021-05-18T08:14:11+00:00',
      created_by: null,
      modified_by: null,
      virtual_tour_links: null,
      map_popup_description: null,
      type: '',
      distance_from_school_amount: '1.00',
      distance_from_airport_amount: '25.00',
      distance_from_university_amount: '1.00',
      distance_from_beach_amount: null,
      distance_from_hospital_amount: '1.00',
      distance_from_shops_amount: '1.00',
      virtual_tour_link: null,
      video_link: null,
      ref: 110,
      website_status: 'unpublished',
      energy_efficiency_grade: null,
      website_listing_date: null,
      legacy_id: null,
      trashed: null,
      availability_status: null,
      location_description: null,
      amenities_description: null,
      distance_from_rail_station_amount: null,
      distance_from_tube_station_amount: null,
      distance_from_centre_amount: null,
      number_of_units: null,
      starting_price_from: null,
      website_url: null,
      developer_id: null,
      assigned_to: null,
      project_with_type: 'Ceasar Apartment Complex - Rome',
    },
    campaign_id_campaign: null,
    seller_contact: {
      id: '728c634d-62ae-4ed0-a47d-4c043c0c8c33',
      ref: 100014,
      legacy_id: null,
      name: 'Abby Normal',
      first_name: 'Abby',
      last_name: 'Normal',
      nationality: 'IT',
      description: null,
      email: 'abby@normal.com',
      email_2: null,
      phone: '+39-320-5552-08',
      phone_2: null,
      phone_3: null,
      street: '',
      city: 'Milan',
      state: '',
      post_code: '',
      country: 'IT',
      created: '2020-05-25T08:56:25+00:00',
      modified: '2020-05-27T11:55:49+00:00',
      created_by: null,
      modified_by: null,
      role: '',
      contact_id: null,
      title: null,
      trashed: null,
      birthdate: null,
      is_company: false,
      registration_number: null,
      website: null,
      vat_number: null,
      assigned_to: null,
      group_id: null,
      preferred_contact_method: null,
      email_consent: null,
      sms_consent: null,
      phone_consent: null,
      postal_consent: null,
      marketing_consent: null,
      preferred_language: null,
    },
    salesperson_user: {
      id: 'ed48f01f-05c3-4c95-9239-c74e1defe96a',
      username: 'frank@manager.com',
      activation_date: null,
      active: false,
      created: '2020-05-20T10:06:22+00:00',
      modified: '2021-05-10T08:21:03+00:00',
      company: null,
      department: null,
      team: null,
      role: null,
      phone_extension: null,
      reports_to: null,
      employee_code: null,
      is_supervisor: false,
      trashed: null,
      contact_id: 'b3b48cfc-1252-4bcd-a7d4-07749a10d04d',
      legacy_id: null,
      created_by: null,
      modified_by: null,
      is_admin: false,
      name: 'Frank Manager',
      extra: {
        first_name: 'Frank',
        email: 'frank@manager.com',
        phone_mobile: '',
      },
    },
    agent_agent: null,
    location_location: {
      id: '20f1727c-ff8f-4594-8cd6-976c3e6b3d33',
      created: '2021-05-24T07:50:33+00:00',
      modified: '2021-05-24T07:50:33+00:00',
      created_by: null,
      modified_by: null,
      district: 'Roma Capitale',
      area: 'Rome',
      coordinates: null,
      subarea: 'Municipio Roma I',
      country: 'IT',
      ref: 100451,
      trashed: null,
      dist: false,
      display_priority: null,
    },
    modified_by_user: {
      id: 'ed48f01f-05c3-4c95-9239-c74e1defe96a',
      username: 'frank@manager.com',
      activation_date: null,
      active: false,
      created: '2020-05-20T10:06:22+00:00',
      modified: '2021-05-10T08:21:03+00:00',
      company: null,
      department: null,
      team: null,
      role: null,
      phone_extension: null,
      reports_to: null,
      employee_code: null,
      is_supervisor: false,
      trashed: null,
      contact_id: 'b3b48cfc-1252-4bcd-a7d4-07749a10d04d',
      legacy_id: null,
      created_by: null,
      modified_by: null,
      is_admin: false,
      name: 'Frank Manager',
      extra: {
        first_name: 'Frank',
        email: 'frank@manager.com',
        phone_mobile: '',
      },
    },
    created_by_user: {
      id: 'ed48f01f-05c3-4c95-9239-c74e1defe96a',
      username: 'frank@manager.com',
      activation_date: null,
      active: false,
      created: '2020-05-20T10:06:22+00:00',
      modified: '2021-05-10T08:21:03+00:00',
      company: null,
      department: null,
      team: null,
      role: null,
      phone_extension: null,
      reports_to: null,
      employee_code: null,
      is_supervisor: false,
      trashed: null,
      contact_id: 'b3b48cfc-1252-4bcd-a7d4-07749a10d04d',
      legacy_id: null,
      created_by: null,
      modified_by: null,
      is_admin: false,
      name: 'Frank Manager',
      extra: {
        first_name: 'Frank',
        email: 'frank@manager.com',
        phone_mobile: '',
      },
    },
    media: [
      {
        id: '4d5ea3c1-38fc-4b46-9780-ccac6c09739b',
        user_id: null,
        media_type: 'upload',
        reference_id: 'd8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
        related_model: 'Properties',
        related_id: '006251f6-39d4-4944-bb2f-c411e0b8d98b',
        display_order: 0,
        created: '2021-08-13T14:14:26+00:00',
        modified: '2021-08-13T14:14:26+00:00',
        category: {
          id: '16202935-d71e-4e45-af55-607d2e524bfc',
          related_model: 'Properties',
          name: 'photos',
          label: 'Photos',
          created: '2023-11-22T16:09:10+00:00',
          modified: '2023-11-22T16:09:10+00:00',
          signature_required: false,
          public: true,
          created_by: null,
          modified_by: null,
          watermark: false,
          dist: true,
          mime_types: null,
          media_types: null,
        },
        signature_requests: [],
        file: {
          id: 'd8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
          filename: '1628864066.4355-rome15131.jpeg',
          created: '2021-08-13T14:14:26+00:00',
          modified: '2021-08-13T14:14:26+00:00',
          filesystem: 'samples',
          mime_type: 'image/jpeg',
          filesize: 221742,
          original_filename: null,
          original_url: null,
          href: '/api/v2/files/download/media/public/original/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
          thumbnails: {
            huge: '/api/v2/files/download/media/public/huge/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
            xlarge:
              '/api/v2/files/download/media/public/xlarge/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
            large: '/api/v2/files/download/media/public/large/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
            medium:
              '/api/v2/files/download/media/public/medium/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
            small: '/api/v2/files/download/media/public/small/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
            tiny: '/api/v2/files/download/media/public/tiny/d8d52c1e-72f8-47aa-ac1c-cbfb853c61b6',
          },
        },
      },
      {
        id: 'dcccf456-badf-4fa2-a0cd-e99268d6f91a',
        user_id: null,
        media_type: 'upload',
        reference_id: 'fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
        related_model: 'Properties',
        related_id: '006251f6-39d4-4944-bb2f-c411e0b8d98b',
        display_order: 0,
        created: '2021-08-13T14:14:25+00:00',
        modified: '2021-08-13T14:14:25+00:00',
        category: {
          id: 'a8f68789-09b2-43f7-9a1f-7164871b189c',
          related_model: 'Properties',
          name: 'featured_photo',
          label: 'Featured Photo',
          created: '2023-11-22T16:09:10+00:00',
          modified: '2023-11-22T16:09:10+00:00',
          signature_required: false,
          public: true,
          created_by: null,
          modified_by: null,
          watermark: false,
          dist: true,
          mime_types: null,
          media_types: null,
        },
        signature_requests: [],
        file: {
          id: 'fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
          filename: '1628864065.6795-rome1513.jpeg',
          created: '2021-08-13T14:14:25+00:00',
          modified: '2021-08-13T14:14:25+00:00',
          filesystem: 'samples',
          mime_type: 'image/jpeg',
          filesize: 906902,
          original_filename: null,
          original_url: null,
          href: '/api/v2/files/download/media/public/original/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
          thumbnails: {
            huge: '/api/v2/files/download/media/public/huge/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
            xlarge:
              '/api/v2/files/download/media/public/xlarge/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
            large: '/api/v2/files/download/media/public/large/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
            medium:
              '/api/v2/files/download/media/public/medium/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
            small: '/api/v2/files/download/media/public/small/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
            tiny: '/api/v2/files/download/media/public/tiny/fb33f2a3-debb-4e3e-bc3f-10b39f05ffd5',
          },
        },
      },
      {
        id: '9490c2d0-f6e8-4abd-9663-efa484fb6a77',
        user_id: null,
        media_type: 'upload',
        reference_id: '8155605c-f32d-4ebd-a635-fd5bd7f02e50',
        related_model: 'Properties',
        related_id: '006251f6-39d4-4944-bb2f-c411e0b8d98b',
        display_order: 1,
        created: '2021-08-13T14:14:26+00:00',
        modified: '2021-08-13T14:14:26+00:00',
        category: {
          id: '16202935-d71e-4e45-af55-607d2e524bfc',
          related_model: 'Properties',
          name: 'photos',
          label: 'Photos',
          created: '2023-11-22T16:09:10+00:00',
          modified: '2023-11-22T16:09:10+00:00',
          signature_required: false,
          public: true,
          created_by: null,
          modified_by: null,
          watermark: false,
          dist: true,
          mime_types: null,
          media_types: null,
        },
        signature_requests: [],
        file: {
          id: '8155605c-f32d-4ebd-a635-fd5bd7f02e50',
          filename: '1628864066.3978-pexels_vecislavas_popa_1571462.jpg',
          created: '2021-08-13T14:14:26+00:00',
          modified: '2021-08-13T14:14:26+00:00',
          filesystem: 'samples',
          mime_type: 'image/jpeg',
          filesize: 360123,
          original_filename: null,
          original_url: null,
          href: '/api/v2/files/download/media/public/original/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
          thumbnails: {
            huge: '/api/v2/files/download/media/public/huge/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
            xlarge:
              '/api/v2/files/download/media/public/xlarge/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
            large: '/api/v2/files/download/media/public/large/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
            medium:
              '/api/v2/files/download/media/public/medium/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
            small: '/api/v2/files/download/media/public/small/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
            tiny: '/api/v2/files/download/media/public/tiny/8155605c-f32d-4ebd-a635-fd5bd7f02e50',
          },
        },
      },
    ],
    apartment_type: 'standard_apartment',
    building_type: null,
    hotel_type: null,
    house_type: null,
    industrial_type: null,
    investment_type: null,
    land_type: null,
    office_type: null,
    retail_type: null,
    price_field_amount: 601000,
    custom_gb_holding_deposit: null,
    custom_gb_chain_free: null,
    custom_gb_apartment_type: null,
    custom_gb_cloakroom: null,
    custom_gb_age_category: null,
    custom_gb_holiday_home: null,
    custom_gb_fenced: null,
    custom_gb_conservatory: null,
    custom_gb_breakfast_room: null,
    custom_gb_planning_consent: null,
    custom_gb_recently_renovated: null,
    custom_gb_office_type: null,
    custom_gb_local_authority: null,
    custom_gb_retail_type: null,
    custom_gb_condition: null,
    custom_gb_industrial_type: null,
    custom_gb_glazing: null,
    custom_gb_tree_survey: null,
    custom_gb_street_number: null,
    custom_gb_house_type: null,
    custom_gb_building_type: null,
    custom_gb_walk_in_wardrobe: null,
    custom_gb_oil_bill_included: null,
    custom_gb_hotel_type: null,
    custom_gb_road_access: null,
    custom_gb_floor_number: null,
    custom_gb_other_type: null,
    custom_gb_price_qualifier: null,
    custom_gb_water_bill_included: null,
    custom_gb_date_available_from: null,
    custom_gb_gas_bill_included: null,
    custom_gb_security_deposit: null,
    custom_gb_tenure_type: null,
    custom_gb_all_bills_included: null,
    custom_gb_land_type: null,
    custom_gb_wet_room: null,
    custom_gb_reception_rooms: null,
    custom_gb_parking: null,
    custom_gb_mobile_home_type: null,
    custom_gb_stamp_duty: null,
    custom_gb_council_tax_band: null,
    custom_gb_annual_service_charge: null,
    custom_gb_ground_rent: null,
    custom_gb_lease_expires: null,
    custom_gb_council_tax: null,
    custom_gb_lease_start_date: null,
    custom_gb_lease_duration: null,
    custom_gb_orientation: null,
    custom_gb_bat_assessment: null,
    custom_gb_road_safety_report: null,
    custom_gb_outside_space: null,
    custom_gb_planning_consent_number: null,
    custom_gb_master_en_suite: null,
    custom_gb_electricity_bill_included: null,
    custom_gb_reserve_price: null,
    custom_gb_satelite_tv_bill_included: null,
    custom_gb_internet_bill_included: null,
    custom_gb_council_tax_exempt: null,
    custom_gb_separate_utility_room: null,
    custom_gb_entrance_hall: null,
    custom_gb_council_tax_rate_included: null,
    custom_gb_accessibility: null,
    custom_gb_tv_licence_included: null,
    custom_gb_parking_lot_type: null,
    custom_gb_internet_access: null,
    custom_gb_planning_consent_description: null,
  },
};
